### ISSUE TITLE
Nosepipe doesn't work with teamcity-messages plugin

### ISSUE THREAD

**Issue by Ashald** [dmccombs/nosepipe#10]
```
Traceback (most recent call last):
  File "/TeamCity/Agent4/work/9171b2e0bb9e5275/.tox/py27-dj15/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/TeamCity/Agent4/work/9171b2e0bb9e5275/.tox/py27-dj15/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/TeamCity/Agent4/work/9171b2e0bb9e5275/.tox/py27-dj15/lib/python2.7/site-packages/nosepipe.py", line 174, in __call__
    (header + data).decode("latin1"))
Exception: short message body (want 170074996, got 496)
Something went wrong
Message: 
##teamcity[testStarted timestamp='2015-03-18T10:54:36.505' captureStandardOutput='true' flowId='tests.TestCase.test_method (test_emit)' name='tests.TestCase.test_method (test_method)']
   	startTest   
addSuccess
##teamcity[testFinished timestamp='2015-03-18T10:54:36.507' duration='2' flowId='tests.TestCase.test_method (test_method)' name='tests.TestCase.test_method (test_method)']
    stopTest
```

I guess it's because teamcity-messages uses stdout for messages output.

Is it possible to use another mechanism for IPC instead of stdout? Maybe socket or IPC Queue...

**Comment by dmccombs** [comment]
Yeah, the stdout communication of nosepipe is a strange hack. Replacing it with socket communication has been on my wishlist, but I haven't had any time to work on it since I took over maintainership. Pull requests are of course welcome, but it is on my todo list, I'm just not sure when I'll have time to tackle it.

**Comment by jhakonen** [comment]
Hi,

I had similar kind of errors when trying to use nosepipe with my test suite. I'm using 64bit Windows 7. That "short message body" error came usually when errors occured in the tests.
Even those tests which should have passed failed with error output:
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 133, in run
    self.runTest(result)
  File "C:\Python27\lib\site-packages\nose\case.py", line 151, in runTest
    test(result)
  File "C:\Python27\lib\site-packages\nosepipe.py", line 179, in __call__
    getattr(result, method_name)(self._test)
AttributeError: 'ResultProxy' object has no attribute '
addSuccess'
```

To figure out what is going wrong, I added some prints to ProcessIsolationReporterPlugin._send_test_event and SubprocessTestProxy.__call__ methods.

With passing tests this gets written to stdout (using repr()):
 1. header: `\x00\x00\x00\t` = 9 bytes, data: `startTest`
 2. header: `\x00\x00\x00\n` = 10 bytes, data: `addSuccess`

This is what is read from stdout at the calling process:
 1. header: `\x00\x00\x00\t` = 9 bytes, data: `startTest`
 2. header: `\x00\x00\x00\r` = 13 bytes, data: `\naddSuccess\x00\x00`

So the second header's struct packed value 10 is interpreted as end-of-line byte and it gets converted to \r\n which then makes the message parsing go whacky.

I managed to fix this by forcing the subprocess's stdout to binary mode using example from here:
http://stackoverflow.com/a/2374507

I modified setOutputStream method to be like this:
```python
    def setOutputStream(self, stream):
        # we use stdout for IPC, so block all other output
        self._stream = sys.__stdout__
        if sys.platform == 'win32':
            import msvcrt
            msvcrt.setmode(self._stream.fileno(), os.O_BINARY)
        return NullWritelnFile()
```

That seems to have fixed those "short message body" errors as well.

**Comment by dmccombs** [comment]
@jhakonen if you wouldn't mind opening a PR with that change we can likely get that into the next release - I can do some testing myself but I'd like to see at least another Windows user's feedback on it too.

**Comment by jhakonen** [comment]
Here you go @dmccombs.

**Comment by dmccombs** [comment]
One other bug to look into first, but should release this fairly soon.
